### ISSUE TITLE
Equations with an exponent as a factor are solved incorrectly (regression?)

### ISSUE THREAD

**Issue by nickkolok** [together-science/nerdamer-prime#43] opened 2024-03-04 09:21 UTC
If we talk about real roots, we have: $f(x) \cdot e^{g(x)} = 0 \Leftrightarrow f(x) = 0$ (supposing that the domain of $g(x)$ includes the domain of $f(x)$). But with the latest `nerdamer-prime`, we have...
```js
nerdamer.solve('x-6/x - 1 = 0','x').toString();
"[-2,3]"
nerdamer.solve('x^2-x-6=0','x').toString();
"[-2,3]"
nerdamer.solve('(x^2-x-6)*e^2=0','x').toString();
"[-2,3]"
nerdamer.solve('(x^2-x-6)*e^x=0','x').toString();
"[-2,-9007199254740992/4503599627370497,3]"
nerdamer.solve('(x^2-x-6)*e^(x-4)=0','x').toString();
"[-2,3]"
nerdamer.solve('(x^2-x-6)*e^(x+4)=0','x').toString();
"[-2,3]"
nerdamer.solve('(x^2-x-6)*e^(x^2)=0','x').toString();
"[3]"
nerdamer('solve((x^2-x-6)*e^(x^2)=0,x)').toString();
"[3]"
```

However, the original `nerdamer`  gives the right answers:

![image](https://github.com/together-science/nerdamer-prime/assets/5008131/0afcc2a0-aaa7-4f2c-9de9-53523c9b0c4d)

And even
![image](https://github.com/together-science/nerdamer-prime/assets/5008131/86aa3a20-041c-412f-82f4-fe85f9c382ce)

**Comment by gunnarmein-ts** [comment] 2024-03-18 22:45
Thanks for bringing this to my attention. I'll take a look to see what I changed.

**Comment by gunnarmein-ts** [comment] 2024-03-18 23:18
I did some substantial work on the Newton solver. That's possibly the cause. Will investigate.
It looks like the fraction works out to -1.9999999999999996, that might escape my check for unique results.
further, I am noticing that I get much weirder result than you do. There is a great discrepancy between the syntax options:

`x = nerdamer('solve((x^2-x-6)*e^x=0,x)').toString();
console.log(x);
x = nerdamer.solve('(x^2-x-6)*e^x=0','x').toString();
console.log(x);`

I am curious what you see when you use the "internal language" solve?

**Comment by gunnarmein-ts** [comment] 2024-03-19 14:17
@nickkolok I checked in a fix which resolves all scenarios for the internal language version:
`nerdamer('solve(...)')`
The API version is still broken, and I think it has always been. It transforms 
`e^x
=(a/b)^x
=a^x*b^-x`
with a and b both huge, and then for negative x, a^x underflows to 0 at the Newton test points. I don't know how to fix that yet. The internal language version keeps e^x intact and hence works. I will look a little more, but I hope using the internal language version works for you.

**Comment by gunnarmein-ts** [comment] 2024-03-19 15:34
This is now fixed. Thanks!

**Closed by gunnarmein-ts** 2024-03-19 15:34 UTC
