### ISSUE TITLE
arg( 1/i ) returns positive value

### ISSUE THREAD

**Issue by mderumaux** [together-science/nerdamer-prime#53] opened 2024-05-02 10:27 UTC
arg(1/i) should be -pi/2 but it is calculated by nerdamer as +pi/2.

I could not find the bug but putting a stop point to nerdamer.core.js at line 8061, it appears that arg() function receives the denominator "i" value instead of the whole fraction.

Same if I test arg( 1/(1+i) ), arg function calculates arg(1+i).

arg( a/b ) = arg(a) - arg(b) so probably divide function inside arg() should drive to a -1 factor that is not taken into account.

I could not manage to find where division operator inside arg() is computed unfortunately.

thanks for any help, best regards,
Marc

**Comment by gunnarmein-ts** [comment] 2024-05-02 21:32
Thank you! Investigating. In general, I find that the parser makes a lot of initial simplifications before we ever get to the routines. And as nerdamer typically stores something like 1/i as m*i*exp where m is 1 and exp is -1, my first thought is that some routine strips the exponent and forgets to restore it. But we will see!

**Comment by gunnarmein-ts** [comment] 2024-05-02 22:31
the problem is that imagpart() does not handle negative exponents correctly. Fix coming up. Thanks!

**Comment by gunnarmein-ts** [comment] 2024-05-02 22:38
Fixed in nerdamer-prime@1.1.16. Thanks!

**Closed by gunnarmein-ts** 2024-05-02 22:38 UTC

**Comment by gunnarmein-ts** [comment] 2024-05-02 22:49
Make that 1.1.17

**Comment by mderumaux** [comment] 2024-05-03 20:36
Perfect ! Thanks for the patch !
